### ISSUE TITLE
增加工作节点出现AnsibleUndefinedVariable: 'dict object' has no attribute 'manager'

### ISSUE THREAD

**Issue by image2021** [eip-work/kuboard-spray#29]
kuboard-spray 版本：v1.0.0
资源包版本：spray-v2.18.0a-8_k8s-v1.23.5_v1.11-amd64
新增节点类型：计算节点
新增节点系统：ubuntu20.04

截图：
![%{51Z NU5F~J}4$BL{G8RPK](https://user-images.githubusercontent.com/76997679/161245157-b667f0ba-f023-466b-9a0d-7e634736aed6.png)

![J}H%__NSX9LQ$AH %BZ 7V6](https://user-images.githubusercontent.com/76997679/161245218-d0457a49-ae4a-45d0-b03b-b301103f840e.png)

错误文本：
```
TASK [kubernetes/node : nginx-proxy | Write nginx-proxy configuration] *********
task path: /data/resource/spray-v2.18.0a-8_k8s-v1.23.5_v1.11-amd64/content/3rd/kubespray/roles/kubernetes/node/tasks/loadbalancer/nginx-proxy.yml:14
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1066, in do_template
    res = j2_concat(rf)
  File "<template>", line 24, in root
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/template.py", line 139, in run
    resultant = self._templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1103, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'manager'
fatal: [worknode2]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'manager'"
}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
manager                    : ok=16   changed=3    unreachable=0    failed=0    skipped=20   rescued=0    ignored=0   
worknode2                  : ok=437  changed=49   unreachable=0    failed=1    skipped=471  rescued=0    ignored=0   

```

**Comment by mrbruce516** [comment]
同样的问题感觉，在升级到spray-v2.18.0a-8_k8s-v1.23.5_v1.11-amd64这个版本的时候，控制节点升级成功，工作节点在下发calico配置的时候也报错了
![image](https://user-images.githubusercontent.com/46187947/161437858-dacad752-f328-4d75-aed1-d7e876cd2342.png)
