### ISSUE TITLE
环境为一台master 两台node 现在增加一台master2 出现报错

### ISSUE THREAD

**Issue by feiyue2022** [eip-work/kuboard-spray#73]
TASK [download : prep_kubeadm_images | Create kubeadm config] ******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: {%- endfor %}: 'dict object' has no attribute 'node1'
fatal: [master2]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: {% for item in etcd_hosts -%}\n  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}\n{%- endfor %}: 'dict object' has no attribute 'node1'"
}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: {%- endfor %}: 'dict object' has no attribute 'node1'
fatal: [master1]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: {% for item in etcd_hosts -%}\n  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}\n{%- endfor %}: 'dict object' has no attribute 'node1'"
}

应该如何解决？？

**Comment by feiyue2022** [comment]
TASK [download : prep_kubeadm_images | Create kubeadm config] ******************
task path: /data/resource/spray-v2.18.0a-9_k8s-v1.23.14_v1.21-amd64/content/3rd/kubespray/roles/download/tasks/prep_kubeadm_images.yml:17
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1156, in do_template
    res = j2_concat(rf)
  File "<template>", line 19, in root
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'node1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/vars.py", line 98, in __getitem__
    value = self._templar.template(variable)
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 886, in template
    result = self.do_template(
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1193, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'node1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1156, in do_template
    res = j2_concat(rf)
  File "<template>", line 16, in root
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 404, in resolve_or_missing
    val = super(AnsibleContext, self).resolve_or_missing(key)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 243, in resolve_or_missing
    return resolve_or_missing(self, key)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 154, in resolve_or_missing
    return context.parent[key]
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/vars.py", line 100, in __getitem__
    raise AnsibleUndefinedVariable("%s: %s" % (to_native(variable), e.message))
ansible.errors.AnsibleUndefinedVariable: {% for item in etcd_hosts -%}
  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}
{%- endfor %}: 'dict object' has no attribute 'node1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/template.py", line 150, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1193, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: {% for item in etcd_hosts -%}
  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}
{%- endfor %}: 'dict object' has no attribute 'node1'
fatal: [master2]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: {% for item in etcd_hosts -%}\n  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}\n{%- endfor %}: 'dict object' has no attribute 'node1'"
}
<192.168.10.10> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1156, in do_template
    res = j2_concat(rf)
  File "<template>", line 19, in root
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'node1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/vars.py", line 98, in __getitem__
    value = self._templar.template(variable)
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 886, in template
    result = self.do_template(
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1193, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'node1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1156, in do_template
    res = j2_concat(rf)
  File "<template>", line 16, in root
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 404, in resolve_or_missing
    val = super(AnsibleContext, self).resolve_or_missing(key)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 243, in resolve_or_missing
    return resolve_or_missing(self, key)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 154, in resolve_or_missing
    return context.parent[key]
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/vars.py", line 100, in __getitem__
    raise AnsibleUndefinedVariable("%s: %s" % (to_native(variable), e.message))
ansible.errors.AnsibleUndefinedVariable: {% for item in etcd_hosts -%}
  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}
{%- endfor %}: 'dict object' has no attribute 'node1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/template.py", line 150, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/local/lib/python3.8/dist-packages/ansible/template/__init__.py", line 1193, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: {% for item in etcd_hosts -%}
  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}
{%- endfor %}: 'dict object' has no attribute 'node1'
fatal: [master1]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: {% for item in etcd_hosts -%}\n  https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}\n{%- endfor %}: 'dict object' has no attribute 'node1'"
}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
master1                    : ok=135  changed=5    unreachable=0    failed=1    skipped=226  rescued=0    ignored=0   
master2                    : ok=160  changed=6    unreachable=0    failed=1    skipped=245  rescued=0    ignored=0
